import type { Dispatch, FormEvent, SetStateAction } from 'react';
import type { AdminTab, AdminUser, Game, GameForm, GameRestriction, GameRestrictionForm, LibraryDisplayMode, LibraryItem } from '../../types';

export type AdminViewProps = {
  games: Game[];
  users: AdminUser[];
  allUsers: AdminUser[];
  adminTab: AdminTab;
  setAdminTab: (tab: AdminTab) => void;
  adminSearchTerm: string;
  setAdminSearchTerm: (value: string) => void;
  adminTypeFilter: string;
  setAdminTypeFilter: (value: string) => void;
  adminStatusFilter: string;
  setAdminStatusFilter: (value: string) => void;
  selectedUser: AdminUser | null;
  selectedUserId: string;
  adminLibraryItems: LibraryItem[];
  adminGameRestrictions: GameRestriction[];
  adminLibraryMode: LibraryDisplayMode;
  setAdminLibraryMode: (mode: LibraryDisplayMode) => void;
  addGameId: string;
  setAddGameId: (value: string) => void;
  restrictionForm: GameRestrictionForm;
  setRestrictionForm: Dispatch<SetStateAction<GameRestrictionForm>>;
  gameForm: GameForm;
  updateGameForm: (next: Partial<GameForm>, source?: 'toggle' | 'price' | 'old' | 'discount') => void;
  editingGameId: number | null;
  savingGame: boolean;
  resetGameForm: () => void;
  submitGameForm: (event: FormEvent) => void;
  carouselForm: string[];
  setCarouselForm: (value: string[]) => void;
  promoForm: { title: string; text: string };
  setPromoForm: (value: { title: string; text: string }) => void;
  onStore: () => void;
  onSelectUser: (id: string) => void;
  onToggleStatus: (user: AdminUser) => void;
  onToggleRole: (user: AdminUser) => void;
  onAddGame: () => void;
  onRemoveGame: (gameId: number) => void;
  onApplyGameRestriction: () => void;
  onRevokeGameRestriction: (restriction: GameRestriction) => void;
  onEditGame: (game: Game) => void;
  onDeleteGame: (game: Game) => void;
  onSaveCarousel: () => void;
  onSavePromo: () => void;
  currentUserId: string;
};
